"""B4 — ProjectCreate şeması, doğrulama kuralları (spec §3.6) ve otomatik kod (§3.5)."""

import uuid

from app.modules.projects.models import Employer


async def _login(client, user_factory, role_key: str = "system_admin") -> str:
    await user_factory(email=f"{role_key}@t.co", password="parola1234", role_key=role_key)
    resp = await client.post(
        "/auth/login", json={"email": f"{role_key}@t.co", "password": "parola1234"}
    )
    return resp.json()["access_token"]


def _auth(token: str) -> dict[str, str]:
    return {"Authorization": f"Bearer {token}"}


async def test_autogenerated_code_starts_at_001_and_increments(client, user_factory):
    """Kodsuz istekte PRJ-2026-001; ikinci istekte -002 (spec §3.5)."""
    token = await _login(client, user_factory)
    body = {"name": "Proje", "project_type": "taahhut", "is_draft": True}

    first = await client.post("/projects", json=body, headers=_auth(token))
    second = await client.post("/projects", json=body, headers=_auth(token))

    assert first.status_code == 201
    assert first.json()["code"] == "PRJ-2026-001"
    assert second.status_code == 201
    assert second.json()["code"] == "PRJ-2026-002"


async def test_explicit_code_is_respected(client, user_factory):
    token = await _login(client, user_factory)
    resp = await client.post(
        "/projects",
        json={"code": "OZEL-1", "name": "Proje", "project_type": "taahhut", "is_draft": True},
        headers=_auth(token),
    )
    assert resp.status_code == 201
    assert resp.json()["code"] == "OZEL-1"


async def test_contract_on_non_taahhut_returns_422(client, user_factory):
    token = await _login(client, user_factory)
    resp = await client.post(
        "/projects",
        json={
            "name": "Yatırım",
            "project_type": "kendi_yatirim",
            "city": "Ankara",
            "contract": {"contract_no": "SZL-1"},
        },
        headers=_auth(token),
    )
    assert resp.status_code == 422
    assert "yalnızca taahhüt projelerine" in resp.text


async def test_end_before_start_returns_422_with_message(client, user_factory):
    token = await _login(client, user_factory)
    resp = await client.post(
        "/projects",
        json={
            "name": "Proje",
            "project_type": "taahhut",
            "is_draft": True,
            "start_date": "2026-05-01",
            "end_date": "2026-04-01",
        },
        headers=_auth(token),
    )
    assert resp.status_code == 422
    assert resp.json()["detail"] == "Bitiş tarihi başlangıçtan önce olamaz."


async def test_draft_allows_missing_city_but_full_requires_it(client, user_factory):
    token = await _login(client, user_factory)
    draft = await client.post(
        "/projects",
        json={"name": "Taslak", "project_type": "taahhut", "is_draft": True},
        headers=_auth(token),
    )
    assert draft.status_code == 201

    full = await client.post(
        "/projects",
        json={"name": "Tam", "project_type": "taahhut", "is_draft": False},
        headers=_auth(token),
    )
    assert full.status_code == 422


async def test_pct_out_of_range_returns_422(client, user_factory):
    token = await _login(client, user_factory)
    resp = await client.post(
        "/projects",
        json={
            "name": "Proje",
            "project_type": "taahhut",
            "is_draft": True,
            "contract": {"vat_pct": "150"},
        },
        headers=_auth(token),
    )
    assert resp.status_code == 422


async def test_nonexistent_employer_returns_404(client, user_factory):
    token = await _login(client, user_factory)
    resp = await client.post(
        "/projects",
        json={
            "name": "Proje",
            "project_type": "taahhut",
            "is_draft": True,
            "employer_id": str(uuid.uuid4()),
        },
        headers=_auth(token),
    )
    assert resp.status_code == 404
    assert resp.json()["detail"] == "İşveren bulunamadı"


async def test_full_taahhut_snapshots_employer_name(client, db_session, user_factory):
    employer = Employer(name="Güneşkent A.Ş.", tax_number="1234567890")
    db_session.add(employer)
    await db_session.flush()
    token = await _login(client, user_factory)

    resp = await client.post(
        "/projects",
        json={
            "name": "Güneşkent Konut",
            "project_type": "taahhut",
            "city": "Ankara",
            "employer_id": str(employer.id),
            "start_date": "2026-01-01",
            "end_date": "2027-01-01",
            "contract": {
                "contract_no": "SZL-2026-001",
                "signature_date": "2026-01-01",
                "amount": "22400000.00",
                "has_price_escalation": False,
            },
        },
        headers=_auth(token),
    )

    assert resp.status_code == 201
    body = resp.json()
    # employer_name anlık görüntüsü servis tarafından dolduruldu (spec §2.3).
    assert body["employer_name"] == "Güneşkent A.Ş."
    assert body["code"] == "PRJ-2026-001"


async def test_escalation_enabled_requires_index_when_not_draft(client, db_session, user_factory):
    """Kural 5: taslak-dışı, fiyat farkı açık ama endeks boş → 422."""
    employer = Employer(name="Firma")
    db_session.add(employer)
    await db_session.flush()
    token = await _login(client, user_factory)

    resp = await client.post(
        "/projects",
        json={
            "name": "Proje",
            "project_type": "taahhut",
            "city": "Ankara",
            "employer_id": str(employer.id),
            "start_date": "2026-01-01",
            "end_date": "2027-01-01",
            "contract": {
                "contract_no": "SZL-1",
                "signature_date": "2026-01-01",
                "amount": "1000.00",
                "has_price_escalation": True,
            },
        },
        headers=_auth(token),
    )
    assert resp.status_code == 422
    assert resp.json()["detail"] == "Endeks tipi ve baz endeks değeri zorunludur."
