"""modules ve role_permissions tablolari

Revision ID: 9b06c643996e
Revises: e310c169f6df
Create Date: 2026-07-17 15:20:12.924148

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9b06c643996e'
down_revision: str | Sequence[str] | None = 'e310c169f6df'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column(
        'group',
        sa.Enum('GENEL', 'SAHA', 'STOK_SATINALMA', 'MALI', 'SISTEM', name='module_group'),
        nullable=False,
    ),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_key'), 'modules', ['key'], unique=True)
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column(
        'access_level',
        sa.Enum(
            'none', 'view', 'draft', 'request', 'approve', 'full', 'admin', name='access_level'
        ),
        nullable=False,
    ),
    sa.Column(
        'scope',
        sa.Enum('all', 'own', 'project', 'finance', 'stock', 'limited', name='scope'),
        nullable=False,
    ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'module_id', name='uq_role_module')
    )
    op.create_index(
        op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_modules_key'), table_name='modules')
    op.drop_table('modules')
    # ### end Alembic commands ###
    # op.drop_table() bos kolonlu bir Table nesnesi olusturdugu icin
    # SQLAlchemy'nin _on_table_drop event'i (enum tipini otomatik dusuren mekanizma)
    # devreye girmiyor. upgrade() tarafinda CREATE TYPE checkfirst=False ile
    # calistigi icin, bu tipler burada acikca dusurulmezse "alembic downgrade -1"
    # sonrasi "alembic upgrade head" DuplicateObject hatasiyla patlar.
    sa.Enum(name='scope').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='access_level').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='module_group').drop(op.get_bind(), checkfirst=True)
